# Generated by Django 5.1.7 on 2025-04-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contactmessage_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='resolved',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
    ]
