# Generated by Django 5.1.7 on 2025-04-07 07:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_full_name_teacherprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='duration',
        ),
        migrations.AddField(
            model_name='class',
            name='duration_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4),
        ),
    ]
