# Generated by Django 5.1.7 on 2025-04-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
