# Generated by Django 5.1.7 on 2025-04-07 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_subject_class_teacherprofile_classassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
