# Generated by Django 5.1.7 on 2025-04-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_class_duration_per_day_class_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='room',
        ),
    ]
