# Generated by Django 5.1.7 on 2025-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_class_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.CharField(default='Room 101', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='subject_code',
            field=models.CharField(default='Fil 02', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='subject_name',
            field=models.CharField(default='Filipino 01', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.CharField(max_length=50),
        ),
    ]
